// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android'
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCLgwL0Ykk-U2lWzkW7EhzfKVzbI4hMJYI",
      authDomain: "colartive-dev.firebaseapp.com",
      projectId: "colartive-dev",
      storageBucket: "colartive-dev.appspot.com",
      messagingSenderId: "456625951975",
      appId: "1:456625951975:web:e1949c3cbe17660f093e42",
      measurementId: "G-6FXTHTQH0Y");

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyB49nFOEp0nl2Nal-LRVwRVmnRClUr-5vk',
  //   appId: '1:145477013342:android:585ad7d8c65ea9294c49cf',
  //   messagingSenderId: '145477013342',
  //   projectId: 'smart-business-managemen-40121',
  //   storageBucket: 'smart-business-managemen-40121.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCmPFy4LduR9QFJzgxUaKtz7Pb-t2DQveA',
  //   appId: '1:145477013342:ios:7d1b5892da7efa604c49cf',
  //   messagingSenderId: '145477013342',
  //   projectId: 'smart-business-managemen-40121',
  //   storageBucket: 'smart-business-managemen-40121.appspot.com',
  //   androidClientId:
  //       '145477013342-0tevr5mdshpifntfjtuha97gvrl8egtr.apps.googleusercontent.com',
  //   iosClientId:
  //       '145477013342-rvsto9ptlqcl70eqdu1d0l9le4ve01go.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.leadManagement',
  // );
}
