// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1k71DEvBBs0PYQtTgu7cjSGbx5SM4vM',
    appId: '1:819484733556:web:949bc4700ce3305009a121',
    messagingSenderId: '819484733556',
    projectId: 'colartive-1b793',
    authDomain: 'colartive-1b793.firebaseapp.com',
    storageBucket: 'colartive-1b793.firebasestorage.app',
    measurementId: 'G-G388W3479N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-79unTe17Q7INerwOvlJyjvR5OGPDYHY',
    appId: '1:819484733556:android:d68019a27763018609a121',
    messagingSenderId: '819484733556',
    projectId: 'colartive-1b793',
    storageBucket: 'colartive-1b793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJEr3kBOazUhJ3Npu_1qv2HbwPZmvbDg',
    appId: '1:819484733556:ios:19645ed03fb7d58509a121',
    messagingSenderId: '819484733556',
    projectId: 'colartive-1b793',
    storageBucket: 'colartive-1b793.firebasestorage.app',
    iosBundleId: 'com.colartive.wallpapers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJEr3kBOazUhJ3Npu_1qv2HbwPZmvbDg',
    appId: '1:819484733556:ios:19645ed03fb7d58509a121',
    messagingSenderId: '819484733556',
    projectId: 'colartive-1b793',
    storageBucket: 'colartive-1b793.firebasestorage.app',
    iosBundleId: 'com.colartive.wallpapers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG1k71DEvBBs0PYQtTgu7cjSGbx5SM4vM',
    appId: '1:819484733556:web:ebcc0a51bddf831409a121',
    messagingSenderId: '819484733556',
    projectId: 'colartive-1b793',
    authDomain: 'colartive-1b793.firebaseapp.com',
    storageBucket: 'colartive-1b793.firebasestorage.app',
    measurementId: 'G-PGPW6J4YQ3',
  );
}
